## Install Libraries

In [ ]:
%%capture
# Installs Unsloth, Xformers (Flash Attention) and all other packages!
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes

## Initialization

In [ ]:
from unsloth import FastLanguageModel
import torch

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.


In [ ]:
# pretrained model to load from huggingface
model_name = "google/gemma-2b"
# choose any
max_seq_length = 2048
# None for auto detection. Float16 for Tesla T4 and V100, Bfloat16 for Ampere+
dtype = None
# use 4bit quantization to reduce memory usage. Can be False.
load_in_4bit = True
# personal huggingface access token
token = "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"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    token = token,
)

# eos_token is used to mark the end-of-sentence or a piece of text in data
EOS_TOKEN = tokenizer.eos_token

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

==((====))==  Unsloth: Fast Gemma patching release 2024.5
   \\   /|    GPU: Tesla T4. Max memory: 14.748 GB. Platform = Linux.
O^O/ \_/ \    Pytorch: 2.3.0+cu121. CUDA = 7.5. CUDA Toolkit = 12.1.
\        /    Bfloat16 = FALSE. Xformers = 0.0.26.post1. FA = False.
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth


model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/33.6k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 64, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2024.5 patched 18 layers with 18 QKV layers, 18 O layers and 18 MLP layers.


## Data Preparation

In [ ]:
from datasets import load_dataset, DatasetDict

In [ ]:
# mount google drive
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# if the dataset is not splitted it will be loaded as a single `train` set.
# `test` and `validation` sets are needed to be splitted manually.
dataset = load_dataset("csv", data_files="/content/drive/MyDrive/datasets/bangla_sentiment_and_emotion_analysis.csv")

# remove columns that are not needed.
# keep these colmuns and remove the rest.
dataset = dataset.select_columns(["Review", "Emotion"])

# create a copy of the `Emotion` column for encoding it to integer representation
dataset["train"] = dataset["train"].add_column("Emotion_INT", dataset["train"]["Emotion"])

# column to stratify for splits
stratify_column = "Emotion_INT"

# convert/encode the column to ClassLabel object
dataset = dataset.class_encode_column(stratify_column)

#print(dataset['train'].features)
#print(dataset['train'].features['Emotion'].names)
#print(dataset['train'].features['Emotion'].str2int(['Happy', 'Anger']))

print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Casting to class labels:   0%|          | 0/78130 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['Review', 'Emotion', 'Emotion_INT'],
        num_rows: 78130
    })
})


In [ ]:
# split the main dataset into `train` and `test` sets
train_with_test_valid = dataset["train"].train_test_split(test_size=0.2, stratify_by_column=stratify_column, seed=1)

# split the `test` set from the newly splitted dataset into,
# 80% test and 20% evaluation sets
test_valid = train_with_test_valid["test"].train_test_split(test_size=0.5, stratify_by_column=stratify_column, seed=1)

# combine everything into a single DatasetDict
dataset = DatasetDict({
    "train": train_with_test_valid["train"],
    "test": test_valid["train"],
    "eval": test_valid["test"]})

# remove the `Emotion_INT` column now that the dataset has been split
dataset = dataset.remove_columns("Emotion_INT")

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['Review', 'Emotion'],
        num_rows: 62504
    })
    test: Dataset({
        features: ['Review', 'Emotion'],
        num_rows: 9375
    })
    eval: Dataset({
        features: ['Review', 'Emotion'],
        num_rows: 6251
    })
})


In [ ]:
print("TRAIN:", dataset["train"][0])
print("TEST:", dataset["test"][0])
print("EVAL:", dataset["eval"][0])

print("\n", dataset["train"].features)

TRAIN: {'Review': 'Long lasting perfume. Performance is quite surprising. It smells too sweet and musky. It is not a regular used perfume. But it is price worthy for its performance. In winter it will perform well, I guess.', 'Emotion': 'Love'}
TEST: {'Review': 'It was delivered quickly in a pristine condition. The product is good considering the price range. I am happy with the service', 'Emotion': 'Happy'}
EVAL: {'Review': 'Thanks for daraz', 'Emotion': 'Love'}

 {'Review': Value(dtype='string', id=None), 'Emotion': Value(dtype='string', id=None)}


In [ ]:
# create prompt for `train` and `eval` sets
def format_train_prompt(data):
  text = data["Review"]
  emotion = data["Emotion"]

  prompts = []

  for text, emotion in zip(text, emotion):
    # must add EOS_TOKEN, otherwise your generation will go on forever!
    #text = f"""Classify the Text into Happy, Love, Sadness, Anger or Fear.
    text = f"""generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[{text}] = {emotion}""".strip() + EOS_TOKEN

    prompts.append(text)

  return { "Prompt" : prompts, }

# creat prompt for `test` set
def format_test_prompt(data):
  text = data["Review"]
  emotion = data["Emotion"]

  prompts = []

  for text, emotion in zip(text, emotion):
    # must add EOS_TOKEN, otherwise your generation will go on forever!
    text = f"""generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[{text}] = """.strip()

    prompts.append(text)

  return { "Prompt" : prompts, }


# format the prompts for fine-tuning
# this adds a `Prompt` column in the datasets
dataset["train"] = dataset["train"].map(format_train_prompt, batched = True,)
dataset["eval"] = dataset["eval"].map(format_train_prompt, batched = True,)

dataset["test"] = dataset["test"].map(format_test_prompt, batched = True,)

print(dataset)

Map:   0%|          | 0/62504 [00:00<?, ? examples/s]

Map:   0%|          | 0/6251 [00:00<?, ? examples/s]

Map:   0%|          | 0/9375 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['Review', 'Emotion', 'Prompt'],
        num_rows: 62504
    })
    test: Dataset({
        features: ['Review', 'Emotion', 'Prompt'],
        num_rows: 9375
    })
    eval: Dataset({
        features: ['Review', 'Emotion', 'Prompt'],
        num_rows: 6251
    })
})


In [ ]:
print("TEST PROMPT:\n", dataset["test"][5]["Prompt"])
print("TEST EMOTION: ", dataset["test"][5]["Emotion"])

TEST PROMPT:
 generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[Product quality is too much high that i didn’t expect in this price range. Highly recommendable product. Thank you seller, Thanks to Daraz.] =
TEST EMOTION:  Happy


## Fine Tuning

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

In [ ]:
training_args = TrainingArguments(
  per_device_train_batch_size = 4,
  gradient_accumulation_steps = 4,
  warmup_steps = 2,
  max_steps = 161,
  learning_rate = 2e-4,
  fp16 = not is_bfloat16_supported(),
  bf16 = is_bfloat16_supported(),
  logging_steps = 1,
  #optim = "adamw_8bit",
  optim = "paged_adamw_32bit",
  weight_decay = 0.01,
  lr_scheduler_type = "cosine",
  output_dir = "outputs",
  seed = 3407,
)

In [ ]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset["train"],
    eval_dataset = dataset["eval"],
    dataset_text_field = "Prompt",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = training_args
)

/usr/local/lib/python3.10/dist-packages/multiprocess/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()


Map (num_proc=2):   0%|          | 0/62504 [00:00<?, ? examples/s]

Map (num_proc=2):   0%|          | 0/6251 [00:00<?, ? examples/s]

max_steps is given, it will override any value given in num_train_epochs


In [ ]:
# Show current memory stats

gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.748 GB.
2.523 GB of memory reserved.


In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs = 1
   \\   /|    Num examples = 62,504 | Num Epochs = 1
O^O/ \_/ \    Batch size per device = 4 | Gradient Accumulation steps = 4
\        /    Total batch size = 16 | Total steps = 219
 "-____-"     Number of trainable parameters = 78,446,592


## Inference/Prediction

In [ ]:
import numpy as np
import pandas as pd

from tqdm import tqdm
from transformers import TextStreamer

In [ ]:
print("TEST:\n",dataset["test"][7]["Prompt"])
print("TEST EMOTION:\n", dataset["test"][7]["Emotion"])

print()

print("TEST:\n",dataset["test"][10]["Prompt"])
print("TEST EMOTION:\n", dataset["test"][10]["Emotion"])

TEST:
 generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[যেমনটা আশা করেছিলাম তেমন-ই পেয়েছি।
ধন্যবাদ দারাজ সঠিক পন্যটি দেওয়ার জন্য।] =
TEST EMOTION:
 Happy

TEST:
 generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[অনেক ভালো ছিলো] =
TEST EMOTION:
 Love


In [40]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

#inputs = tokenizer( [dataset["test"][14]["Prompt"] ], return_tensors = "pt").to("cuda")

# prompt = dataset["test"][10]["Prompt"],
prompt = f"""generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[খারাপ না তেমন] = """.strip()

inputs = tokenizer([prompt], return_tensors = "pt").to("cuda")

text_streamer = TextStreamer(tokenizer)
output = model.generate(**inputs, streamer = text_streamer, max_new_tokens=3, temperature=0.0, use_cache = True)

<bos>generate_prompt
Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[খারাপ না তেমন] = Sadness<eos>


### Predict on test set

In [59]:
def predict(test_set, model, tokenizer):
  test_set_labels = []
  labels = ["Happy", "Love", "Sadness", "Anger", "Fear", "None"]

  for i in tqdm(range(len(test_set))):
    prompt = test_set.iloc[i]["Prompt"]

    input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(**input_ids, max_new_tokens=2, temperature=0.0)
    result = tokenizer.decode(outputs[0])

    answer = result.split("=")[-1].lower()

    if labels[0].lower() in answer:
      test_set_labels.append(labels[0])
    elif labels[1].lower() in answer:
      test_set_labels.append(labels[1])
    elif labels[2].lower() in answer:
      test_set_labels.append(labels[2])
    elif labels[3].lower() in answer:
      test_set_labels.append(labels[3])
    elif labels[4].lower() in answer:
      test_set_labels.append(labels[4])
    elif labels[5].lower() in answer:
      test_set_labels.append(labels[5])
    else:
      test_set_labels.append("None")

  return test_set_labels

In [ ]:
test_set_pred = predict(dataset["test"].to_pandas(), model, tokenizer)

  9%|▉         | 845/9375 [02:33<31:17,  4.54it/s]

## Evaluation

In [ ]:
%%capture
!pip install evaluate

import evaluate

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
def evaluate(test_labels, test_predictions):
  labels = ["Happy", "Love", "Sadness", "Anger", "Fear"]
  mapping = {"Happy": 5, "Love": 4, "Sadness": 3, "Anger": 2, "Fear": 1, "None": 0}

  def map_func(x):
    # returns the corresponding int from the mapping.
    # if no label found return 0
    return mapping.get(x, 0)

  test_labels = np.vectorize(map_func)(test_labels)
  test_predictions = np.vectorize(map_func)(test_predictions)

  # Calculate accuracy
  accuracy = accuracy_score(y_true=test_labels, y_pred=test_predictions)
  print(f'Accuracy: {accuracy:.3f}')

  # Generate accuracy report
  unique_labels = set(labels)  # Get unique labels

  for label in unique_labels:
    label_indices = [i for i in range(len(test_labels)) if test_labels[i] == label]
    label_y_true = [test_labels[i] for i in label_indices]
    label_y_pred = [test_predictions[i] for i in label_indices]

    accuracy = accuracy_score(label_y_true, label_y_pred)

    print(f'Accuracy for label {label}: {accuracy:.3f}')

  # Generate classification report
  class_report = classification_report(y_true=test_labels, y_pred=test_predictions)
  print('\nClassification Report:')
  print(class_report)

  # Generate confusion matrix
  conf_matrix = confusion_matrix(y_true=test_labels, y_pred=test_predictions, labels=[0, 1, 2, 3, 4, 5])
  print('\nConfusion Matrix:')
  print(conf_matrix)

In [ ]:
def evaluate(test_labels, test_predictions):
  labels = ["Happy", "Love", "Sadness", "Anger", "Fear"]
  mapping = {"Happy": 5, "Love": 4, "Sadness": 3, "Anger": 2, "Fear": 1, "None": 0}

  def map_func(x):
    # returns the corresponding int from the mapping.
    # if no label found return 0
    return mapping.get(x, 0)

  test_labels = np.vectorize(map_func)(test_labels)
  test_predictions = np.vectorize(map_func)(test_predictions)

  # Calculate accuracy
  hug_accuracy = accuracy_metric.compute(predictions=predictions, references=labels),
  accuracy = accuracy_score(y_true=test_labels, y_pred=test_predictions)
  print(f'Hug Accuracy: {hug_accuracy:.3f}')
  print(f'Accuracy: {accuracy:.3f}')

  # Generate accuracy report
  unique_labels = set(labels)  # Get unique labels

  for label in unique_labels:
    label_indices = [i for i in range(len(test_labels)) if test_labels[i] == label]
    label_y_true = [test_labels[i] for i in label_indices]
    label_y_pred = [test_predictions[i] for i in label_indices]

    accuracy = accuracy_score(label_y_true, label_y_pred)

    print(f'Accuracy for label {label}: {accuracy:.3f}')

  # Generate classification report
  class_report = classification_report(y_true=test_labels, y_pred=test_predictions)
  print('\nClassification Report:')
  print(class_report)

  # Generate confusion matrix
  conf_matrix = confusion_matrix(y_true=test_labels, y_pred=test_predictions, labels=[0, 1, 2, 3, 4, 5])
  print('\nConfusion Matrix:')
  print(conf_matrix)

        "precision":


In [ ]:
test_set_labels

In [ ]:
dataset["test"].to_pandas()["Emotion"]

0         Happy
1          Love
2         Happy
3         Happy
4          Love
         ...   
9370       Love
9371      Happy
9372    Sadness
9373      Happy
9374      Happy
Name: Emotion, Length: 9375, dtype: object

In [ ]:
evaluate(dataset["test"].to_pandas()["Emotion"], test_set_labels)

Accuracy: 0.000
Accuracy for label Fear: nan
Accuracy for label Sadness: nan
Accuracy for label Anger: nan


/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: R

Accuracy for label Love: nan
Accuracy for label Happy: nan

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00     139.0
           2       0.00      0.00      0.00     380.0
           3       0.00      0.00      0.00     784.0
           4       0.00      0.00      0.00    2476.0
           5       0.00      0.00      0.00    5596.0

    accuracy                           0.00    9375.0
   macro avg       0.00      0.00      0.00    9375.0
weighted avg       0.00      0.00      0.00    9375.0


Confusion Matrix:
[[   0    0    0    0    0    0]
 [ 139    0    0    0    0    0]
 [ 380    0    0    0    0    0]
 [ 784    0    0    0    0    0]
 [2476    0    0    0    0    0]
 [5596    0    0    0    0    0]]


/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:

In [ ]:
accuracy_metric = evaluate.load("accuracy")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")

# define an evaluation function to pass into trainer later
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=1)

    return {
        "accuracy": accuracy_metric.compute(predictions=predictions, references=labels),
        "precision": precision_metric.compute(predictions=predictions, references=labels),
        }

In [ ]:
# training stats
trainer_stats.metrics

{'train_runtime': 611.8318,
 'train_samples_per_second': 5.727,
 'train_steps_per_second': 0.358,
 'total_flos': 7292099330506752.0,
 'train_loss': 0.9226225904405934,
 'epoch': 0.05606041213362345}

In [29]:
evaluation_stats = trainer.evaluate()

In [30]:
# evaluation stats
evaluation_stats

{'eval_loss': 0.9732468724250793,
 'eval_runtime': 353.4124,
 'eval_samples_per_second': 17.688,
 'eval_steps_per_second': 2.213,
 'epoch': 0.05606041213362345}

## Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [31]:
model.save_pretrained("emotion_analysis_gemma_2b") # Local saving
tokenizer.save_pretrained("emotion_analysis_gemma_2b")
# model.push_to_hub("your_name/lora_model", token = "...") # Online saving
# tokenizer.push_to_hub("your_name/lora_model", token = "...") # Online saving

/usr/local/lib/python3.10/dist-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 401 Client Error. (Request ID: Root=1-66549bed-7754f5996bf10c8363960417;f4da4ec9-65e6-468c-bd23-165e003176dd)

Cannot access gated repo for url https://huggingface.co/google/gemma-2b/resolve/main/config.json.
Access to model google/gemma-2b is restricted. You must be authenticated to access it. - silently ignoring the lookup for the file config.json in google/gemma-2b.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in google/gemma-2b - will assume that the vocabulary was not modified.
  warnings.warn(


('emotion_analysis_gemma_2b/tokenizer_config.json',
 'emotion_analysis_gemma_2b/special_tokens_map.json',
 'emotion_analysis_gemma_2b/tokenizer.model',
 'emotion_analysis_gemma_2b/added_tokens.json',
 'emotion_analysis_gemma_2b/tokenizer.json')

In [32]:
!tar -czvf emotion_analysis_gemma_2b__27_05_2024_safetensors.tar.gz /content/emotion_analysis_gemma_2b

tar: Removing leading `/' from member names
/content/emotion_analysis_gemma_2b/
/content/emotion_analysis_gemma_2b/tokenizer.json
/content/emotion_analysis_gemma_2b/tokenizer_config.json
/content/emotion_analysis_gemma_2b/adapter_model.safetensors
/content/emotion_analysis_gemma_2b/tokenizer.model
/content/emotion_analysis_gemma_2b/special_tokens_map.json
/content/emotion_analysis_gemma_2b/adapter_config.json
/content/emotion_analysis_gemma_2b/README.md


Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# alpaca_prompt = You MUST copy from above!

inputs = tokenizer(
[
    alpaca_prompt.format(
        "What is a famous tall tower in Paris?", # instruction
        "", # input
        "", # output - leave this blank for generation!
    ),
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs)

You can also use Hugging Face's `AutoModelForPeftCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
    # I highly do NOT suggest - use Unsloth if possible
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
        "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        load_in_4bit = load_in_4bit,
    )
    tokenizer = AutoTokenizer.from_pretrained("lora_model")

## GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [Wiki page](https://github.com/unslothai/unsloth/wiki#gguf-quantization-options)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

In [33]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
if False: model.push_to_hub_gguf("hf/model", tokenizer, token = "")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "f16", token = "")

# Save to q4_k_m GGUF
if True: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q4_k_m", token = "")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q5_k_m", token = "")

Unsloth: You have 1 CPUs. Using `safe_serialization` is 10x slower.
We shall switch to Pytorch saving, which will take 3 minutes and not 30 minutes.
To force `safe_serialization`, set it to `None` instead.
Unsloth: Kaggle/Colab has limited disk space. We need to delete the downloaded
model which will save 4-16GB of disk space, allowing you to save on Kaggle/Colab.
Unsloth: Will remove a cached repo with size 5.0G


Unsloth: Merging 4bit and LoRA weights to 16bit...
Unsloth: Will use up to 6.2 out of 12.67 RAM for saving.


100%|██████████| 18/18 [00:01<00:00, 11.80it/s]


Unsloth: Saving tokenizer... Done.
Unsloth: Saving model... This might take 5 minutes for Llama-7b...
Unsloth: Saving model/pytorch_model-00001-of-00002.bin...
Unsloth: Saving model/pytorch_model-00002-of-00002.bin...
Done.


Unsloth: Converting gemma model. Can use fast conversion = False.


==((====))==  Unsloth: Conversion from QLoRA to GGUF information
   \\   /|    [0] Installing llama.cpp will take 3 minutes.
O^O/ \_/ \    [1] Converting HF to GUUF 16bits will take 3 minutes.
\        /    [2] Converting GGUF 16bits to q4_k_m will take 20 minutes.
 "-____-"     In total, you will have to wait around 26 minutes.

Unsloth: [0] Installing llama.cpp. This will take 3 minutes...


Unsloth: We must use f16 for non Llama and Mistral models.


Unsloth: [1] Converting model at model into f16 GGUF format.
The output location will be ./model-unsloth.F16.gguf
This will take 3 minutes...
INFO:hf-to-gguf:Loading model: model
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Setting special token type bos to 2
INFO:gguf.vocab:Setting special token type eos to 1
INFO:gguf.vocab:Setting special token type unk to 3
INFO:gguf.vocab:Setting special token type pad to 0
INFO:gguf.vocab:Setting add_bos_token to True
INFO:gguf.vocab:Setting add_eos_token to False
INFO:gguf.vocab:Setting special token type prefix to 67
INFO:gguf.vocab:Setting special token type suffix to 69
INFO:gguf.vocab:Setting special token type middle to 68
INFO:gguf.vocab:Setting special token type eot to 107
INFO:hf-to-gguf:Exporting model to 'model-unsloth.F16.gguf'
INFO:hf-to-gguf:gguf: loading model weight map from 'pytorch_model.bin.index.json'
INFO:hf-to-gg

In [34]:
!cp -r '/content/model-unsloth.Q4_K_M.gguf' /content/drive/MyDrive/models/emotion_analysis_gemma_2b__27_05_2024.gguf

!cp -r /content/emotion_analysis_gemma_2b__27_05_2024_safetensors.tar.gz /content/drive/MyDrive/models/